apiVersion: batch/v1
kind: CronJob
metadata:
  name: princetrail-cronjob
  namespace: default
spec:
  schedule: "0 2 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: worker1
            image: pricetrail
            imagePullPolicy: IfNotPresent
            command: ["python", "-c", "from scraper.scraper import run; run()"]
          restartPolicy: OnFailure
